# Generated by Django 5.0.6 on 2024-06-19 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит этот пользователь. Пользователь получит все разрешения, предоставленные каждой из их групп.', related_name='custom_user_set', related_query_name='user', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Конкретные разрешения для этого пользователя.', related_name='custom_user_set', related_query_name='user', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректное имя пользователя. Это значение может содержать только буквы, цифры и символы @/./+/-/_.', regex='^[\\w.@+-\\u0400-\\u04FF]+$')]),
        ),
    ]
